#!/bin/bash
echo ''
echo ''
echo 'pppp    pppp    RRRR'
echo 'p   p   p   p   R   R'
echo 'p   p   p   p   R   R'
echo 'pppp    pppp    RRRR'
echo 'p       p       R   R'
echo 'p       p       R   R'
echo 'p       p       R   R'
echo ''
echo ''

PROJECT_NAME=local_dns_tracker

echo  'Submit keys'
scp ~/Projects/$PROJECT_NAME/keys_pr.py stancia@172.16.0.20:~/proj/$PROJECT_NAME/keys.py
ssh -tt stancia@172.16.0.20 << "EOF"
cd ~/proj/local_dns_tracker/
git fetch --all
git reset --hard origin/master
echo 'Git Pull -- Ok'
logout
EOF